package com.myspace.tasksignals;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class address implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer homeno;
	private java.lang.String road;

	public address() {
	}

	public java.lang.Integer getHomeno() {
		return this.homeno;
	}

	public void setHomeno(java.lang.Integer homeno) {
		this.homeno = homeno;
	}

	public java.lang.String getRoad() {
		return this.road;
	}

	public void setRoad(java.lang.String road) {
		this.road = road;
	}

	public address(java.lang.Integer homeno, java.lang.String road) {
		this.homeno = homeno;
		this.road = road;
	}

}