package com.myspace.tasksignals;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class caseobj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String casestatus;
	private java.lang.String processinstanceid;
	private com.myspace.tasksignals.customer customer;
	private com.myspace.tasksignals.address address;

	private java.lang.String caseid;

	private java.lang.String source;

	public caseobj() {
	}

	public java.lang.String getCasestatus() {
		return this.casestatus;
	}

	public void setCasestatus(java.lang.String casestatus) {
		this.casestatus = casestatus;
	}

	public java.lang.String getProcessinstanceid() {
		return this.processinstanceid;
	}

	public void setProcessinstanceid(java.lang.String processinstanceid) {
		this.processinstanceid = processinstanceid;
	}

	public com.myspace.tasksignals.customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(com.myspace.tasksignals.customer customer) {
		this.customer = customer;
	}

	public com.myspace.tasksignals.address getAddress() {
		return this.address;
	}

	public void setAddress(com.myspace.tasksignals.address address) {
		this.address = address;
	}

	public java.lang.String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(java.lang.String caseid) {
		this.caseid = caseid;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public caseobj(java.lang.String casestatus,
			java.lang.String processinstanceid,
			com.myspace.tasksignals.customer customer,
			com.myspace.tasksignals.address address, java.lang.String caseid,
			java.lang.String source) {
		this.casestatus = casestatus;
		this.processinstanceid = processinstanceid;
		this.customer = customer;
		this.address = address;
		this.caseid = caseid;
		this.source = source;
	}

}